---

- include_vars: "{{ private_dir }}/p.yml"

- name: install docker-py
  command: pip install docker-py

- name: upstart docker conf - ulimit open files
  copy: src=etc/init/upstart_docker.conf dest=/etc/init/docker.conf
        owner=root
        group=root
        mode=644
#notify: reload docker
  tags: upstart-docker

- name: setup quay.io /root/.docker.cfg
  copy: src='{{ private_dir }}/../docker/docker.cfg'
        dest=/root/.docker.cfg
        owner=root
        group=root
        mode=600

- name: ensure /data dir
  file: path=/data state=directory

- name: ensure /data/mariadb directory for mariadb55 container
  file: path=/data/mariadb state=directory

#docker run -d --env="APP_PATH=https://sendy.okfn.org DATABASE_PASS=***" -p  127.0.0.1:8001:80 --link="mariadb55:db" --name sendy.okfn.org  okfn/opensendy:1.1.9~2
- name: ensure sendy container is running
  docker: image=okfn/opensendy:1.1.9~2 ports=127.0.0.1:8001:80 name=sendy.okfn.org links=mariadb55:db env="DATABASE_PASS={{ sendy_okfn_org_db_pw }},APP_PATH=https://sendy.okfn.org"
  tags: start-sendy
